name: heart_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.2.1
  google_generative_ai: ^0.4.6
  shared_preferences: ^2.2.2
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.5
  permission_handler: ^12.0.1
  flutter_sound: ^9.30.0
  path_provider: ^2.1.5
  geolocator: ^14.0.2
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true